# Import Libraries

In [73]:
import pandas as pd

import numpy as np

df = pd.read_csv('dirty_dataset.csv')

# Data Inspection

In [74]:
df.head()

,customer_id,age,income,education,marital_status,credit_score,loan_amount,employment_years,default_status,last_payment_date,phone_number,email,city,state,zip_code,product_type,purchase_frequency,avg_monthly_spend,last_login,account_created
0,CUST001,25.0,45000,Bachelor,Married,720,15000.0,3,0,12/15/2023,-677,john.doe@email.com,New York,NY,10001,credit_card,monthly,850.50,1/15/2024 10:30,3/15/2020
1,CUST002,NaN,75000,Master,Divorced,680,25000.0,8,1,11/20/2023,555-0124,jane.smith@,Chicago,IL,60601,personal_loan,quarterly,1200.75,1/10/2024 14:22,7/22/2019
2,CUST003,28.0,52000,Bachelor,Married,750,18000.0,4,0,12/1/2023,555-0125,bob.wilson@email.com,Los Angeles,CA,90210,credit_card,weekly,650.25,1/20/2024 9:15,1/10/2021
3,CUST004,42.0,95000,PhD,Married,800,35000.0,12,0,12/30/2023,555-0126,alice.brown@email.com,Houston,TX,77001,mortgage,annually,2500.00,1/18/2024 16:45,5/30/2018
4,CUST005,31.0,38000,HighSchool,Single,620,12000.0,2,1,10/15/2023,555-0127,charlie.davis@,Miami,FL,33101,personal_loan,monthly,450.00,1/12/2024 11:30,2/14/2022

In [75]:
df.sample()

,customer_id,age,income,education,marital_status,credit_score,loan_amount,employment_years,default_status,last_payment_date,phone_number,email,city,state,zip_code,product_type,purchase_frequency,avg_monthly_spend,last_login,account_created
28,CUST029,35.0,70000,Bachelor,Divorced,730,25000.0,7,0,12/17/2023,555-0151,benjamin.wright@email.com,Baltimore,MD,21201,credit_card,monthly,1080.5,2/7/2024 15:45,1/26/2019

In [76]:
df.tail()

,customer_id,age,income,education,marital_status,credit_score,loan_amount,employment_years,default_status,last_payment_date,phone_number,email,city,state,zip_code,product_type,purchase_frequency,avg_monthly_spend,last_login,account_created
45,CUST046,37.0,75000,Master,Married,760,27000.0,8,0,12/19/2023,555-0168,steven.edwards@email.com,Wichita,KS,67201,personal_loan,quarterly,1050.00,2/24/2024 16:20,11/3/2019
46,CUST047,31.0,54000,Bachelor,Single,700,18000.0,4,0,12/12/2023,555-0169,tracy.collins@,Arlington,TX,76001,Unknown,30,790.75,2/25/2024 9:50,7/29/2020
47,CUST048,35.0,68000,NaN,Divorced,730,24000.0,7,0,12/17/2023,555-0170,ulrich.stewart@email.com,New Orleans,LA,70112,mortgage,annually,1900.50,2/26/2024 11:05,4/16/2019
48,CUST049,-29.0,49000,Bachelor,Married,690,17000.0,3,0,12/9/2023,555-0171,vanessa.sanchez@,Las Vegas,NV,89109,personal_loan,monthly,680.00,2/27/2024 13:40,6/2/2021
49,CUST050,32.0,58000,Associate,Divorced,710,19000.0,5,0,12/13/2023,555-0172,walter.morris@,Portland,OR,97205,3,bi-weekly,850.25,2/28/2024 15:15,12/19/2020

In [77]:
df.shape

(50, 20)

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         50 non-null     object
 1   age                 49 non-null     float64
 2   income              50 non-null     object
 3   education           48 non-null     object
 4   marital_status      48 non-null     object
 5   credit_score        49 non-null     object
 6   loan_amount         49 non-null     float64
 7   employment_years    50 non-null     object
 8   default_status      50 non-null     object
 9   last_payment_date   49 non-null     object
 10  phone_number        50 non-null     object
 11  email               50 non-null     object
 12  city                50 non-null     object
 13  state               48 non-null     object
 14  zip_code            50 non-null     object
 15  product_type        50 non-null     object
 16  purchase_frequency  50 non-null     object
 17  avg_monthly_spend   49 non-null     float64
 18  last_login          49 non-null     object
 19  account_created     49 non-null     object
dtypes: float64(3), object(17)
memory usage: 7.9+ KB

In [79]:
df.describe()

             age   loan_amount  avg_monthly_spend
count  49.000000     49.000000          49.000000
mean   30.326531  22877.551020        1132.346939
std    13.919991  10244.170401         977.586896
min   -32.000000  10000.000000        -920.500000
25%    28.000000  16000.000000         680.000000
50%    31.000000  19000.000000         850.250000
75%    37.000000  26000.000000        1100.000000
max    47.000000  60000.000000        4500.000000

# Checking for Missing Values

In [80]:
df.isna().sum()

customer_id           0
age                   1
income                0
education             2
marital_status        2
credit_score          1
loan_amount           1
employment_years      0
default_status        0
last_payment_date     1
phone_number          0
email                 0
city                  0
state                 2
zip_code              0
product_type          0
purchase_frequency    0
avg_monthly_spend     1
last_login            1
account_created       1
dtype: int64

# Checking for Duplicates

In [81]:
df.duplicated().sum()

0

# Checking and Changing Data Types

In [110]:
df['income'] = df['income'].replace('35k', '35000')

df['income'] = pd.to_numeric(df['income'], errors='coerce')

df['credit_score'] = pd.to_numeric(df['credit_score'], errors='coerce')

df['employment_years'] = pd.to_numeric(
    df['employment_years'], errors='coerce'
)

df['default_status'] = pd.to_numeric(
    df['default_status'], errors='coerce'
)

df['employment_years'] = pd.to_numeric(
    df['employment_years'], 
    errors="coerce"
)

In [83]:
df.dtypes

customer_id            object
age                   float64
income                  int64
education              object
marital_status         object
credit_score          float64
loan_amount           float64
employment_years      float64
default_status        float64
last_payment_date      object
phone_number           object
email                  object
city                   object
state                  object
zip_code               object
product_type           object
purchase_frequency     object
avg_monthly_spend     float64
last_login             object
account_created        object
dtype: object

# Data Cleaning

### Fixing Spelling Errors

In [84]:
df['marital_status'] = df['marital_status'].replace('divorsed', 'divorced')

In [85]:
df['education'] = df['education'].replace('HighSchool', 'High School')

## Fixing Invalid Values

### Fixing Ages

In [86]:
df.loc[df['age'] < 0, 'age'] = pd.NA

In [89]:
df['age'] = df['age'].fillna(df['age'].median())

### Fixing Inconsistent Values in 'product_type' and 'purchase_frequency' Columns

In [106]:
df['product_type'] = df['product_type'].replace('3', 'Unknown')

In [88]:
df['purchase_frequency'] = df['purchase_frequency'].replace('30', 'Unknown')

### Fixing missing Values in 'credit_score' column

In [90]:
df['credit_score'] = df['credit_score'].fillna(df['credit_score'].median())

### Fixing missing Values in 'employment_years' Column

In [111]:
df['employment_years'] = df['employment_years'].fillna(
    df['employment_years'].median()
)

### Eliminating Inconsistent Values in 'email' column

In [116]:
invalid_email = ~df['email'].str.contains(
    r"^[^@\s]+@[^@\s]+\.[^@\s]+$",
    regex=True,
    na=False
)

df.loc[invalid_email, ['customer_id', 'email']]

   customer_id email
1      CUST002  <NA>
4      CUST005  <NA>
7      CUST008  <NA>
10     CUST011  <NA>
12     CUST013  <NA>
14     CUST015  <NA>
16     CUST017  <NA>
19     CUST020  <NA>
21     CUST022  <NA>
22     CUST023  <NA>
25     CUST026  <NA>
27     CUST028  <NA>
30     CUST031  <NA>
32     CUST033  <NA>
36     CUST037  <NA>
38     CUST039  <NA>
41     CUST042  <NA>
43     CUST044  <NA>
44     CUST045  <NA>
46     CUST047  <NA>
48     CUST049  <NA>
49     CUST050  <NA>

In [ ]:
df.loc[invalid_email, 'email'] = pd.NA

In [114]:
df['phone_number'] = (
    df['phone_number']
    .str.replace(r"\D", "", regex=True)
)

In [115]:
df['phone_number']

0            677
1        5550124
2        5550125
3        5550126
4        5550127
5        5550128
6        5550129
7        5550130
8        5550131
9        5550132
10    5551330000
11       5550134
12       5550135
13       5550136
14       5550137
15       5550138
16       5550139
17       5550140
18       5550141
19       5550142
20       5550143
21       5550144
22       5550145
23       5550146
24       5550147
25       5550148
26       5550149
27       5550150
28       5550151
29       5550152
30       5550153
31       5550154
32       5550155
33       5550156
34       5550157
35       5550158
36       5550159
37       5550160
38       5550161
39       5550162
40       5550163
41       5550164
42       5550165
43       5550166
44       5550167
45       5550168
46       5550169
47       5550170
48       5550171
49       5550172
Name: phone_number, dtype: object

### Fixing Invalid Values in 'Zip_code' Column

In [95]:
df['zip_code'] = df['zip_code'].str.replace('"', '', regex=False)

In [96]:
df['zip_code'] = df['zip_code'].str.zfill(5)

In [97]:
df['zip_code']

0     10001
1     60601
2     90210
3     77001
4     33101
5     98101
6     02101
7     85001
8     80201
9     30301
10    94101
11    48201
12    89101
13    97201
14    78701
15    55401
16    37201
17    32801
18    92101
19    64101
20    43201
21    33601
22    15201
23    28201
24    46201
25    53201
26    38101
27    40201
28    21201
29    87101
30    85701
31    93701
32    95801
33    85201
34    23451
35    68101
36    80901
37    27601
38    33125
39    90801
40    30309
41    94601
42    55403
43    74101
44    44101
45    67201
46    76001
47    70112
48    89109
49    97205
Name: zip_code, dtype: object

### Fixing Invalid Values in 'avg_monthly_spend' Column

In [98]:
df[df['avg_monthly_spend'] < 0]

,customer_id,age,income,education,marital_status,credit_score,loan_amount,employment_years,default_status,last_payment_date,phone_number,email,city,state,zip_code,product_type,purchase_frequency,avg_monthly_spend,last_login,account_created
5,CUST006,29.0,58000,Bachelor,Single,710.0,20000.0,5.0,0.0,12/25/2023,5550128,diana.garcia@email.com,Seattle,WA,98101,credit_card,bi-weekly,-780.5,1/22/2024 13:20,11/8/2020
24,CUST025,33.0,61000,Master,Married,760.0,20000.0,5.0,0.0,12/11/2023,5550147,xavier.hall@email.com,Indianapolis,IN,46201,personal_loan,quarterly,-920.5,2/3/2024 14:25,6/14/2020

In [99]:
df.loc[df['avg_monthly_spend'] < 0, 'avg_monthly_spend'] = pd.NA

In [100]:
df['avg_monthly_spend'] = df['avg_monthly_spend'].fillna(
    df['avg_monthly_spend'].median()
)

In [101]:
df['avg_monthly_spend']

0      850.50
1     1200.75
2      650.25
3     2500.00
4      450.00
5      850.50
6     3200.75
7      520.25
8     1100.00
9      950.75
10     720.50
11    2800.25
12     380.00
13     980.50
14     680.75
15    4500.00
16     890.25
17     750.50
18    1050.75
19     580.00
20    2600.50
21     820.25
22     490.75
23    1150.00
24     850.50
25     710.75
26    3100.25
27     620.00
28    1080.50
29     850.25
30     850.50
31    2700.00
32     420.50
33    1020.25
34     760.00
35     980.75
36     690.50
37    2400.25
38     580.00
39     920.50
40     810.75
41     650.25
42    2200.00
43     880.50
44     720.25
45    1050.00
46     790.75
47    1900.50
48     680.00
49     850.25
Name: avg_monthly_spend, dtype: float64

## Fixing Date Columns

In [102]:
df['last_payment_date'] = pd.to_datetime(df['last_payment_date'], errors='coerce')

In [103]:
df['last_login'] = pd.to_datetime(df['last_login'], errors='coerce')

In [104]:
df['account_created'] = pd.to_datetime(df['account_created'], errors='coerce')

In [105]:
df.dtypes

customer_id                   object
age                          float64
income                         int64
education                     object
marital_status                object
credit_score                 float64
loan_amount                  float64
employment_years             float64
default_status               float64
last_payment_date     datetime64[ns]
phone_number                  object
email                         object
city                          object
state                         object
zip_code                      object
product_type                  object
purchase_frequency            object
avg_monthly_spend            float64
last_login            datetime64[ns]
account_created       datetime64[ns]
dtype: object

In [69]:
df.isna().sum()

customer_id            0
age                    0
income                 0
education              2
marital_status         2
credit_score           0
loan_amount            1
employment_years       2
default_status         1
last_payment_date      1
phone_number           0
email                 22
city                   0
state                  2
zip_code               0
product_type           0
purchase_frequency     0
avg_monthly_spend      0
last_login             1
account_created        1
dtype: int64

## Cleaning Categorical Columns

In [70]:
categorical_columns = [
    'education',
    'marital_status',
    'state',
    'product_type'
]

for column in categorical_columns:
    df[column] = df[column].fillna(df[column].mode()[0])

In [71]:
df.head(10)

,customer_id,age,income,education,marital_status,credit_score,loan_amount,employment_years,default_status,last_payment_date,phone_number,email,city,state,zip_code,product_type,purchase_frequency,avg_monthly_spend,last_login,account_created
0,CUST001,25.0,45000,Bachelor,Married,720.0,15000.0,3.0,0.0,2023-12-15,677,john.doe@email.com,New York,NY,10001,credit_card,monthly,850.50,2024-01-15 10:30:00,2020-03-15
1,CUST002,32.0,75000,Master,Divorced,680.0,25000.0,8.0,1.0,2023-11-20,5550124,<NA>,Chicago,IL,60601,personal_loan,quarterly,1200.75,2024-01-10 14:22:00,2019-07-22
2,CUST003,28.0,52000,Bachelor,Married,750.0,18000.0,4.0,0.0,2023-12-01,5550125,bob.wilson@email.com,Los Angeles,CA,90210,credit_card,weekly,650.25,2024-01-20 09:15:00,2021-01-10
3,CUST004,42.0,95000,PhD,Married,800.0,35000.0,12.0,0.0,2023-12-30,5550126,alice.brown@email.com,Houston,TX,77001,mortgage,annually,2500.00,2024-01-18 16:45:00,2018-05-30
4,CUST005,31.0,38000,High School,Single,620.0,12000.0,2.0,1.0,2023-10-15,5550127,<NA>,Miami,FL,33101,personal_loan,monthly,450.00,2024-01-12 11:30:00,2022-02-14
5,CUST006,29.0,58000,Bachelor,Single,710.0,20000.0,5.0,0.0,2023-12-25,5550128,diana.garcia@email.com,Seattle,WA,98101,credit_card,bi-weekly,850.50,2024-01-22 13:20:00,2020-11-08
6,CUST007,45.0,110000,Master,Married,820.0,50000.0,15.0,0.0,2023-12-28,5550129,frank.miller@email.com,Boston,MA,02101,mortgage,annually,3200.75,2024-01-19 08:45:00,2017-09-12
7,CUST008,26.0,42000,Associate,Married,650.0,15000.0,1.0,1.0,2023-09-10,5550130,<NA>,Phoenix,AZ,85001,personal_loan,monthly,520.25,NaT,2023-01-05
8,CUST009,38.0,78000,Bachelor,Divorced,740.0,28000.0,9.0,0.0,2023-12-20,5550131,henry.taylor@email.com,Denver,CO,80201,credit_card,monthly,1100.00,2024-01-21 12:00:00,2019-12-03
9,CUST010,33.0,63000,Master,Married,760.0,22000.0,6.0,0.0,2023-12-18,5550132,iris.white@email.com,Atlanta,GA,30301,personal_loan,quarterly,950.75,2024-01-16 17:30:00,2020-08-20

### Rechecking Missing Values

In [72]:
df.isna().sum()

customer_id            0
age                    0
income                 0
education              0
marital_status         0
credit_score           0
loan_amount            1
employment_years       2
default_status         1
last_payment_date      1
phone_number           0
email                 22
city                   0
state                  0
zip_code               0
product_type           0
purchase_frequency     0
avg_monthly_spend      0
last_login             1
account_created        1
dtype: int64

# Saving Cleaned Data

In [107]:
df.to_csv('cleaned_dataset.csv', index=False)